### ISSUE TITLE
Index Out of Range

### ISSUE THREAD

**Issue by SkyHyperV** [piccolomo/plotext#100]
I get the following error intermittently even though my SQL query for the data against my DB returns the right number of rows for both 'dates' and my 'data':

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 4475, in main
    get_account_info(logger, TDSession, data_all, account_id)
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 2380, in get_account_info
    print_account_nlv_plot(logger, account_id)
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 3708, in print_account_nlv_plot
    plt.show()
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_core.py", line 183, in show
    figure.show()
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_figure.py", line 250, in show
    self.build()
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_figure.py", line 257, in build
    self._build_matrix()
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_figure.py", line 283, in _build_matrix
    self.monitor.build_plot(*self._size) if not self.monitor.fast_plot else None
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_monitor.py", line 847, in build_plot
    x[s], y[s], mxy = hd_group(x[s], y[s], xf[s], yf[s])
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_monitor.py", line 1196, in hd_group
    m[yi][xi][yk][xk] = 1
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/bin/pmtlottotracker", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 4480, in main
    get_account_info(logger, TDSession, data_all, 1)
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 2380, in get_account_info
    print_account_nlv_plot(logger, account_id)
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 3708, in print_account_nlv_plot
    plt.show()
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_core.py", line 183, in show
    figure.show()
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_figure.py", line 250, in show
    self.build()
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_figure.py", line 257, in build
    self._build_matrix()
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_figure.py", line 283, in _build_matrix
    self.monitor.build_plot(*self._size) if not self.monitor.fast_plot else None
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_monitor.py", line 847, in build_plot
    x[s], y[s], mxy = hd_group(x[s], y[s], xf[s], yf[s])
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_monitor.py", line 1196, in hd_group
    m[yi][xi][yk][xk] = 1
IndexError: list index out of range

**Comment by SkyHyperV** [comment]
Looks like running: plot.clf() before starting the plot helps. Will keep testing.

**Comment by piccolomo** [comment]
Hello @SkyHyperV 

thanks for your feedback and taking the time to drop the issue. Could I kindly ask you for a minimum code that produces that error?

Thanks

**Comment by SkyHyperV** [comment]
Code below, but I believe its functioning properly now that I run plt.clf() before any of my rendering code. I didn't realize this plot had some "memory" or something which caused me some issues with it showing stale data even though it should have rendered a new graph. Anyhow, code below but it seems to be working with clf() called:

    try:
        today = datetime.date.today()
        current_year = today.strftime('%Y')

        plt.clf()
        plt.date_form('Y-m-d')
        plt.plotsize(120, 25)
        plt.theme('clear')

        conn = sqlite3.connect(DB_PATH, isolation_level=None)
        conn.row_factory = lambda cursor, nlv_row: nlv_row[0]
        c = conn.cursor()
        nlvs = c.execute(f'SELECT nlv FROM account_info where account_id = {account_id} and '
                         f'date like "{current_year}-%" order by date asc').fetchall()
        dates = c.execute(f'SELECT date FROM account_info where account_id = {account_id} and '
                          f'date like "{current_year}-%" order by date asc').fetchall()
        conn.close()

        plt.plot(dates, nlvs)
        plt.title("YTD NLV")
        plt.xlabel("Date")
        plt.ylabel("NLV")
        plt.show()

    except (IndexError, TypeError):
        pass

**Comment by SkyHyperV** [comment]
Actually I'm also trying a bar chart (code below) with the same date format (2022-01-03) and values are floats like 200.5 for "net premium" but getting the following stacktrace:

Code:
plt.clf()
    plt.date_form('Y-m-d')
    plt.plotsize(120, 25)
    plt.theme('clear')
    plt.plot(dates, net_premium)
    plt.bar(['500'], ['2022-01-03'], orientation="horizontal", width=3/5)
    if CONFIG.fee > 0:
        plt.title(f"Daily Net Premium [Fee ${CONFIG.fee}]")
    else:
        plt.title(f"Daily Net Premium")
    plt.show()
    
Error:
Traceback (most recent call last):
  File "/home/me/.local/bin/pmtlottotracker", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 4631, in main
    calculate_sum_daily(logger, 1)
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 821, in calculate_sum_daily
    print_daily_summary_plot(logger, account_id)
  File "/home/me/.local/lib/python3.10/site-packages/pmtlottotracker/app.py", line 3783, in print_daily_summary_plot
    plt.bar(['500'], ['2022-01-03'], orientation="horizontal", width=3/5)
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_core.py", line 142, in bar
    return figure._active.bar(*args, xside = xside, yside = yside, marker = marker, color = color, fill = fill, width = width, orientation = orientation, label = label, minimum = minimum)
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_figure.py", line 208, in bar
    self.monitor.draw_bar(*args, xside = xside, yside = yside, marker = marker, color = color, fill = fill, width = width, orientation = orientation, label = label, minimum = minimum) if self._no_plots else [[self._get_subplot(row, col).bar(*args, xside = xside, yside = yside, marker = marker, color = color, fill = fill, width = width, orientation = orientation, label = label, minimum = minimum) for col in self._Cols] for row in self._Rows]
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_monitor.py", line 436, in draw_bar
    self.bar_ylim = update_bar_ylim(self.bar_ylim + y + [minimum])
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_monitor.py", line 1212, in update_bar_ylim
    bar_lim = update_bar_xlim(y)
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_monitor.py", line 1208, in update_bar_xlim
    bar_lim = get_lim(y)
  File "/home/me/.local/lib/python3.10/site-packages/plotext/_monitor.py", line 1091, in get_lim
    m, M = (m, M) if m is None or m != M else (0.5 * m, 1.5 * m) if m == M != 0 else (-1, 1)
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by SkyHyperV** [comment]
Ignore... I had the bar chart backwards in the input. My issues are largely resolved using the clf() and fixing the ordering. Will close case.

**Comment by piccolomo** [comment]
Hi @SkyHyperV,

no problem, glad you found a way out. Any other feedback more then welcomed, even by e-mail.

All the best,
Savino

**Comment by piccolomo** [comment]
Hi @SkyHyperV, I may delete this issue in the foloowing days, but if you or someone else think I should not, please let me know. Any other issue is more then welcomed.
Thanks,
Savino
