### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by SkyHyperV** [piccolomo/plotext#104]
I'm getting the following stack trace on the code below. I checked both my dates and nlvs lists and they both have 137 entries in each list so the contents match up. I cannot reproduce this error but one of my users reported it.

dates = ['01-03', ...]
nlvs = [150.35, ...]

        today = datetime.date.today()
        current_year = today.strftime('%Y')

        plt.clf()
        plt.date_form('m-d')
        plt.plotsize(120, 25)
        plt.theme('pro')

        conn = sqlite3.connect(DB_PATH, isolation_level=None)
        conn.row_factory = lambda cursor, nlv_row: nlv_row[0]
        c = conn.cursor()
        nlvs = c.execute(f'SELECT nlv FROM account_info where account_id = {account_id} and '
                         f'date like "{current_year}-%" order by date asc').fetchall()
        dates = c.execute(f'SELECT strftime("%m-%d", date) FROM account_info where account_id = {account_id} and '
                          f'date like "{current_year}-%" order by date asc').fetchall()

        conn.close()

        plt.plot(dates, nlvs)
        plt.title(f"{current_year}: NLV")
        plt.xlabel("Date")
        plt.ylabel("NLV")
        plt.show()

Traceback (most recent call last):
  File "C:\Users\LoP\anaconda3\envs\backtesting\Scripts\-script.py", line 33, in <module>
    sys.exit(load_entry_point('', 'console_scripts', '')())
  File "c:\users\LoP\desktop\--\src\\app.py", line 4637, in main
    get_account_info(logger, TDSession, data_all, 1)
  File "c:\users\LoP\desktop\--\src\\app.py", line 2417, in get_account_info
    print_account_nlv_plot(logger, account_id)
  File "c:\users\LoP\desktop\--\src\\app.py", line 3758, in print_account_nlv_plot
    plt.show()
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_core.py", line 183, in show
    figure.show()
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_figure.py", line 250, in show
    self.build()
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_figure.py", line 257, in build
    self._build_matrix()
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_figure.py", line 283, in _build_matrix
    self.monitor.build_plot(*self._size) if not self.monitor.fast_plot else None
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_monitor.py", line 753, in build_plot
    xlabels = [self.xlabels[i] if isinstance(self.xticks[i], list) else self.date.times_to_string(xticks_scaled[i]) if self.x_date[i] else get_labels(xticks_scaled[i]) for i in r2]
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_monitor.py", line 753, in <listcomp>
    xlabels = [self.xlabels[i] if isinstance(self.xticks[i], list) else self.date.times_to_string(xticks_scaled[i]) if self.x_date[i] else get_labels(xticks_scaled[i]) for i in r2]
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_date.py", line 58, in times_to_string
    return [self.time_to_string(el, input_form) for el in times]
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_date.py", line 58, in <listcomp>
    return [self.time_to_string(el, input_form) for el in times]
  File "C:\Users\LoP\anaconda3\envs\backtesting\lib\site-packages\plotext\_date.py", line 55, in time_to_string
    return self.datetime_to_string(dt.fromtimestamp(time + self.time0), output_form)
OSError: [Errno 22] Invalid argument

**Comment by SkyHyperV** [comment]
Could my issues be related to version 5.0.2? I run: pip install plotext but it doesn't install 5.1

**Comment by SkyHyperV** [comment]
Another update, I updated the library and even try to pass in fixed lists like the below and stilit crashes with the stacktracek. The 'bar' charts work but plt.plot(dates, nlvs) doesnt. Here's a sample data:

dates = ['01-03', '01-15', '01-31', '02-14', '02-28']
nlvs = [123456789, 133456789, 143456789, 123996789, 11346789]

still produces stacktrace/error

**Comment by piccolomo** [comment]
Hi @SkyHyperV , I finally updated `plotext` and the new version should solve this issue. 

![image](https://user-images.githubusercontent.com/56689657/188204572-d43900b3-1414-451c-ac0f-05f62141e398.png)

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. 

Thanks a lot for your inputs and all the best,
Savino

**Comment by 34j** [comment]
Seems this issue has still not been resolved.
```shell
PS > python
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import plotext as plt; plt.clf();
>>> dates = ['01-03']
>>> nlvs = [1]
>>> plt.date_form('m-d')
>>> plt.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv\Lib\site-packages\plotext\_core.py", line 293, in show
    _figure.show()
  File "venv\Lib\site-packages\plotext\_figure.py", line 319, in show
    self.build()
    ^^^^^^^^^^^^
  File "venv\Lib\site-packages\plotext\_figure.py", line 326, in build
    self._build_matrix()
  File "venv\Lib\site-packages\plotext\_figure.py", line 332, in _build_matrix
    self.monitor.build_plot() if not self.monitor.fast_plot else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\plotext\_build.py", line 85, in build_plot
    xlabels = [self.date.times_to_string(xticks_rescaled[i]) if self.x_date[i] else ut.get_labels(xticks_rescaled[i]) if xticks_to_set[i] else self.xlabels[i] for i in r2]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\plotext\_build.py", line 85, in <listcomp>
    xlabels = [self.date.times_to_string(xticks_rescaled[i]) if self.x_date[i] else ut.get_labels(xticks_rescaled[i]) if xticks_to_set[i] else self.xlabels[i] for i in r2]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\plotext\_date.py", line 59, in times_to_string
    return [self.time_to_string(el, input_form) for el in times]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\plotext\_date.py", line 59, in <listcomp>
    return [self.time_to_string(el, input_form) for el in times]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\plotext\_date.py", line 56, in time_to_string
    return self.datetime_to_string(dt.fromtimestamp(time + self.time0), output_form)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
PS > pip show plotext
Name: plotext
Version: 5.2.8
Summary: plotext plots directly on terminal
Home-page: https://github.com/piccolomo/plotext
Author: Savino Piccolomo
Author-email: piccolomo@gmail.com
License: MIT
Location: venv\Lib\site-packages
Requires:
Required-by:
```

**Comment by 34j** [comment]
Understood, this happens only when the date is not complete ( `Y/m/d H:M:S` ) or when there is only one element to plot
