### ISSUE TITLE
Simple Bar Plots do not Support 0 Data

### ISSUE THREAD

**Issue by mhorst314** [piccolomo/plotext#153]
Hi,

Thanks for your nice library. I think I found a bug: I get a float division by zero error if I try to plot a stacked bar graph and all the data for the bars is zero.  

To reproduce:
```
>>> import plotext as plt
>>> plt.simple_stacked_bar(["foo"], [[0]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mhorst/.local/lib/python3.10/site-packages/plotext/_core.py", line 208, in simple_stacked_bar
    _glob.simple_stacked_bar(*args, width = width, marker = marker, colors = colors, title = title, labels = labels)
  File "/home/mhorst/.local/lib/python3.10/site-packages/plotext/_global.py", line 28, in simple_stacked_bar
    x, y, Y, width = ut.bar_data(*args, width = width)
  File "/home/mhorst/.local/lib/python3.10/site-packages/plotext/_utility.py", line 752, in bar_data
    Yi = [[round(el / dx, 0) for el in y] for y in Y]
  File "/home/mhorst/.local/lib/python3.10/site-packages/plotext/_utility.py", line 752, in <listcomp>
    Yi = [[round(el / dx, 0) for el in y] for y in Y]
  File "/home/mhorst/.local/lib/python3.10/site-packages/plotext/_utility.py", line 752, in <listcomp>
    Yi = [[round(el / dx, 0) for el in y] for y in Y]
ZeroDivisionError: float division by zero
>>> 

```
As a work-around I just put an if-statement in my code to not call simple_stacked_bar when this occurs. But it would be nice if the function could handle this corner case.

Kind regards,

Martijn

**Comment by piccolomo** [comment]
Hi @mhorst314, thanks for reporting, nice spotted. 

I have a vague idea why the error is there, but I would need to code it. I will update and thanks for dropping the report!

Savino

**Comment by piccolomo** [comment]
Hi @mhorst314,

I have solved this issue, and published the result on [PyPi](https://pypi.org/project/plotext/) as well. 

If you could double check, it would be helpful.

Thanks,
Savino

**Comment by mhorst314** [comment]
Yes, it works. Thanks :)
