### ISSUE TITLE
Tkinter Demo not Working with Version 5.2.8

### ISSUE THREAD

**Issue by thedesignatedgeek** [piccolomo/plotext#157]
In Issue 156 you suggested that I try the Tkinter Kitten demo.  You also suggest that to make it work I replace plt.figure with plt.active().
I tried that, but I try to run, I get

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/greg/.pyenv/versions/3.9.5/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/greg/Desktop/PageTests/Page-7.6rc1/test12-plotext/kitenplot.py", line 87, in plot_command
    self.add_plot()
  File "/home/greg/Desktop/PageTests/Page-7.6rc1/test12-plotext/kitenplot.py", line 121, in add_plot
    self.canvas = plt.uncolorize(self.canvas)
  File "/home/greg/.pyenv/versions/3.9.5/lib/python3.9/site-packages/plotext/_core.py", line 384, in uncolorize
    return _ut.uncolorize(string)
  File "/home/greg/.pyenv/versions/3.9.5/lib/python3.9/site-packages/plotext/_utility.py", line 382, in uncolorize
    while colored():
  File "/home/greg/.pyenv/versions/3.9.5/lib/python3.9/site-packages/plotext/_utility.py", line 381, in <lambda>
    colored = lambda: ansi_begin in string
TypeError: argument of type '_figure_class' is not iterable

`
I know there is probably something very simple that I'm missing, but I don't know how to fix it.

Greg

**Comment by thedesignatedgeek** [comment]
Yes, it now works correctly.
Thank you!

Greg

**Comment by piccolomo** [comment]
Thanks for feedback
