### ISSUE TITLE
`IndexError: list index out of range` at `plotext/_build.py"`, line 261

### ISSUE THREAD

**Issue by Jipok** [piccolomo/plotext#185]
<details><summary>code</summary>

```python
#!/usr/bin/env python3
import plotext as plt
#from subprocess import check_output
#import psutil
import time

CMD = "sensors amdgpu-pci-0500 | grep PPT | grep -oP '(?<=cap = )(.?\d+)'"
TARGET_TEMP = 83
CAP_MIN = 20
CAP_MAX = 180
CHART_HISTORY_COUNT = 55
plt.theme("pro")

# Prefill arrays for good chart after start
a_temp = []
a_powercap = []
#temp = psutil.sensors_temperatures()["amdgpu"][0].current
#powercap = int(check_output(CMD, shell = True).decode('utf-8'))
temp = 1
powercap = 1
for i in range(1, CHART_HISTORY_COUNT):
        a_temp.append(temp)
        a_powercap.append(powercap)

while True:
        # Trim chart
        if len(a_temp) > CHART_HISTORY_COUNT:
                a_temp = a_temp[1:]
                a_powercap = a_powercap[1:]
        # Get data
        #temp = psutil.sensors_temperatures()["amdgpu"][0].current
        a_temp.append(temp)
        #powercap = int(check_output(CMD, shell = True).decode('utf-8'))
        a_powercap.append(powercap)
        # Plot temp
        plt.clear_terminal()
        plt.clear_data()
        label = "Temp %s°C" % temp
        plt.plot(a_temp, label = label, color = "red")
        plt.ylabel(label)
        plt.ylim(20, 100)
        plt.hline(TARGET_TEMP, "green")
        # Plot power cap
        label = "Powercap %sW" % powercap
        plt.plot(a_powercap, label = label, yside = "right", color = "blue")
        plt.ylabel(label, yside = "right")
        plt.ylim(CAP_MIN - 10, CAP_MAX + 10, yside = "right")
        plt.show()
        # Limit power
        newcap = powercap
        if temp < TARGET_TEMP:
                cap_step = TARGET_TEMP - temp
                newcap = int(min(powercap + cap_step, CAP_MAX))
        if temp > TARGET_TEMP:
                cap_step = pow(temp - TARGET_TEMP, 2)
                newcap = int(max(powercap - cap_step, CAP_MIN))
        if newcap != powercap:
                check_output("/opt/rocm/bin/rocm-smi --setpoweroverdrive " + str(newcap), shell = True)

        time.sleep(1)
```
</details>
<details><summary>log</summary>

```
Traceback (most recent call last):
  File "/root/./main_dup.py", line 50, in <module>
    plt.show()
  File "/usr/lib/python3.11/site-packages/plotext/_core.py", line 293, in show
    _figure.show()
  File "/usr/lib/python3.11/site-packages/plotext/_figure.py", line 319, in show
    self.build()
    ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/plotext/_figure.py", line 326, in build
    self._build_matrix()
  File "/usr/lib/python3.11/site-packages/plotext/_figure.py", line 332, in _build_matrix
    self.monitor.build_plot() if not self.monitor.fast_plot else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/plotext/_build.py", line 261, in build_plot
    [[self.matrix.insert_element(col_start + S + i, row_end - 1 - s, marker[s][i], color[s][i], style[s][i]) for i in range(3)] for s in range(l)] if legend_test else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/plotext/_build.py", line 261, in <listcomp>
    [[self.matrix.insert_element(col_start + S + i, row_end - 1 - s, marker[s][i], color[s][i], style[s][i]) for i in range(3)] for s in range(l)] if legend_test else None
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/plotext/_build.py", line 261, in <listcomp>
    [[self.matrix.insert_element(col_start + S + i, row_end - 1 - s, marker[s][i], color[s][i], style[s][i]) for i in range(3)] for s in range(l)] if legend_test else None
                                                                                   ~~~~~~~~^^^
IndexError: list index out of range
```
</details>
This is a real script that I use, I replaced receiving real data and now it should run and give the same result on any hardware.
For some reason, this problem only occurs the first time the script is launched after the server is rebooted. If the script runs successfully, then after that it will always run successfully.

**Comment by jc-audet** [comment]
This issue arrises because the lines your trying to plot does not appear in the y axis limits of [20,100], which causes empty arrays in the build. It is fixed with the piece of code in the PR above.

**Comment by cap-txt** [comment]
I have the same issue, which only shows up if I pass a `label` to the plot and not otherwise.

**Comment by piccolomo** [comment]
Just to update and apologise: I have been quite busy rewriting the package from ground up and will update.

**Comment by piccolomo** [comment]
Hi @jc-audet, and sorry for the long silence, and for leaving your pull request open until you closed it yourself.

  Your diagnosis was right: in version 5, a signal whose points all fell outside the limits kept its label but had no markers left, and the legend then raised the `IndexError` of #185.

  Version 6 of [plotext](https://github.com/piccolomo/plotext) ([PyPI](https://pypi.org/project/plotext/)), published very soon on both, is a rewrite where the points outside the limits are dropped before drawing and the legend lists only what it has, so the crash is gone. Running the two-axes plot of #185
  with every value below its limits, which is what used to crash, now gives an empty canvas:

  ```python
  import plotext as plt

  fig = plt.figure

  fig.draw(fig.signal([1] * 55, marker = "hd").label("Temp 1 C").lines())
  fig.ruler("y", "left").lim(20, 100).alignment(lim = "edge")

  fig.draw(fig.signal([1] * 55, yside = "right", marker = "hd").label("Powercap 1 W").lines())
  fig.ruler("y", "right").lim(10, 190).alignment(lim = "edge")

  fig.line(83, orientation = "horizontal", pixel = "green")
  fig.title("every value below its limits: empty canvas, no crash")
  fig.show()
  ```

<img width="960" height="432" alt="Image" src="https://github.com/user-attachments/assets/8ca13108-d1ac-4e2a-9e66-6301e1e30a5e" />

  Note on the limits themselves (the version 5 ones are described [here](https://github.com/piccolomo/plotext/blob/master/readme/settings.md#plot-limits)): by default they are centered, which leaves half a character of tolerance, so a point just below the lower limit can still be drawn on the bottom row;
  adding `alignment(lim = "edge")`, as above, pins them exactly. Making plain limits behave that way too is on the plan for a next version.

  Thanks for the fix and for the patience,

  Regards,
  Savino
