### ISSUE TITLE
Out of bound on a simple_stacked_bar with more than 16 stacked dataset 

### ISSUE THREAD

**Issue by mielune** [piccolomo/plotext#190]
Hi,

I try to build a simple_stacked_bar  with 22 stacked datasets but the lib crash on the colors 
Limit with 16 datasets is working but I need all of the 22.

Can I have a workaround ? 
It seems to be linked to the `colors[i]` out of range line 733
The ability to setup my own colors list ?

With all datasets :
![image](https://github.com/piccolomo/plotext/assets/8350742/74fb3bcc-c900-4bc6-9e85-601e4e43a880)
![image](https://github.com/piccolomo/plotext/assets/8350742/a526f05d-c3c0-443b-8ca8-00187e9081f2)

With only 16 datasets :
![image](https://github.com/piccolomo/plotext/assets/8350742/e8a01832-9ed9-4982-8a01-24fc3b0b282b)

Kind regards,

**Comment by mielune** [comment]
I will try with 

```python
colors[i % len(colors)]
```

in both lines 733 and 775 to rotate on the colors if not enough available, without crash.

**Comment by piccolomo** [comment]
Hello, sorry I am a bit absent from solving issue recently, as I am (slowly) rebuilding the package from ground up.

Can I ask you to send the code you used to produce the error?

Thanks for reporting and your inputs

**Comment by mielune** [comment]
Hi,

A small example to reproduce this issue: with 19 items it work fine, but with 20 failed.

```python
import plotext as plt
from random import random


nb_items = 20  # Work fine with 19
nb_data = 30

items = [f"a{x+1}" for x in range(nb_items)]
data = [[int(random() * 100) for y in range(nb_data)] for x in range(nb_items)]
labels = [f"l{y+1}" for y in range(nb_data)]

plt.simple_stacked_bar(labels, data, labels=items, title="Test")
plt.show()
```


Result:
```
Traceback (most recent call last):
  File "/home/techlab/drill/drillqueries/test.py", line 12, in <module>
    plt.simple_stacked_bar(labels, data, labels=items, title="Test")
  File "/home/techlab/drill/drillqueries/.venv/lib/python3.11/site-packages/plotext/_core.py", line 208, in simple_stacked_bar
    _glob.simple_stacked_bar(*args, width = width, marker = marker, colors = colors, title = title, labels = labels)
  File "/home/techlab/drill/drillqueries/.venv/lib/python3.11/site-packages/plotext/_global.py", line 37, in simple_stacked_bar
    bars = [ut.single_bar(x[i], Y[i], y[i], marker, colors[i]) for i in range(bars)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/techlab/drill/drillqueries/.venv/lib/python3.11/site-packages/plotext/_global.py", line 37, in <listcomp>
    bars = [ut.single_bar(x[i], Y[i], y[i], marker, colors[i]) for i in range(bars)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/techlab/drill/drillqueries/.venv/lib/python3.11/site-packages/plotext/_utility.py", line 733, in single_bar
    bar = [apply_ansi(bar[i], colors[i], 1) for i in range(l)]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/techlab/drill/drillqueries/.venv/lib/python3.11/site-packages/plotext/_utility.py", line 733, in <listcomp>
    bar = [apply_ansi(bar[i], colors[i], 1) for i in range(l)]
                              ~~~~~~^^^
IndexError: list index out of range
```

**Comment by mielune** [comment]
I just created a PR with my fix: https://github.com/piccolomo/plotext/pull/192

Sorry if not in the process, I'm not used to work on Github.

**Comment by piccolomo** [comment]
Just to update and apologise: I have been quite busy rewriting the package from ground up and will update.

**Comment by piccolomo** [comment]
Hi @mielune,

  sorry for the long wait, and thanks both for the report and for the fix you proposed in [Pull Request 192](https://github.com/piccolomo/plotext/pull/192), which named the cause exactly.

  This cannot happen in [plotext 6](https://plotext.readthedocs.io/en/latest/). Colors are no longer read from a list by position: each figure holds a sequence of 16 and hands out the next unused one, starting again from the first when they run out, so any number of groups is drawn and none of them crashes.
  It is described in the [color cycling](https://plotext.readthedocs.io/en/latest/marker.html#color-cycling) section.

  And your other question, a colour list of your own, is answered by [add_theme()](https://plotext.readthedocs.io/en/latest/theme.html#custom-themes), whose `sequence` parameter is exactly that: here twenty two colours for twenty two groups, so none repeats.

  ```python
  import plotext as plt
  from random import random, seed

  seed(0)
  groups, categories = 22, 8

  data = [[int(random() * 100) for _ in range(categories)] for _ in range(groups)]
  names = ["l%d" % (index + 1) for index in range(categories)]

  plt.add_theme("many", sequence = [22 + index for index in range(22)])     # twenty two colors of my own

  fig = plt.figure
  fig.clear()
  fig.plot_size(110, 34)
  fig.theme("many")

  fig.draw(fig.bar(names, data, stacked = True))

  fig.title("twenty two stacked groups, each with its own color")
  fig.show()
  ```

<img width="1320" height="816" alt="Image" src="https://github.com/user-attachments/assets/a83aed51-e167-4442-afb8-a2c969ef9b47" />

  `simple_stacked_bar()` itself is gone: there is one [bar()](https://plotext.readthedocs.io/en/latest/bar.html) method, with `stacked = True`, and the frame-less look is a recipe of it, in the [simple bar style](https://plotext.readthedocs.io/en/latest/bar.html#simple-bar-style) section.

  plotext 6 is out as a beta:
  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

I have also added you to the [credits](https://plotext.readthedocs.io/en/latest/credits.html) of the documentation: your report and your fix are what the colour cycler came from.

  Thanks again for the report,
  Savino
