### ISSUE TITLE
Bar plot produces error if first value is zero.

### ISSUE THREAD

**Issue by clfriede** [piccolomo/plotext#41]
If you try to produce a bar plot with a value of zero in index 0 of the values list, the plot will fail with an error.  Here is an example:

```>>> labels = ['[32-63]', '[64-127]', '[128-255]', '[256-511]', '[512-1023]', '[1024-2047]', '[2048-4095]', '[4096-8191]', '[8192-16383]', '[16384-32767]', '[32768-65535]', '[65536-131071]']
>>> values = [0, 93, 160, 120, 35, 0, 0, 0, 0, 0, 0, 0]
>>> import plotext as plt
>>> plt.clp()
>>> plt.bar(labels,values)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/plotext/plot.py", line 954, in bar
    _fig.subplot.point_color[-1] = _fig.subplot.point_color[-2]
IndexError: list index out of range
```
If you remove the first element of each list above though, every thing works ok.

```>>> import plotext as plt
>>> labels = ['[64-127]', '[128-255]', '[256-511]', '[512-1023]', '[1024-2047]', '[2048-4095]', '[4096-8191]', '[8192-16383]', '[16384-32767]', '[32768-65535]', '[65536-131071]']
>>> values = [93, 160, 120, 35, 0, 0, 0, 0, 0, 0, 0]
>>> plt.clp()
>>> plt.bar(labels,values)
>>> plt.show()
<shows graph>
```

The bar plot should be able to produce a plot when the first value in the list of values is zero.  If you need any additional information from me regarding this issue, please let me know.  Thanks.

**Comment by clfriede** [comment]
This is the same as issue #30.  Closing.
