### ISSUE TITLE
Cannot plot a line of only zeros

### ISSUE THREAD

**Issue by Schmetzler** [piccolomo/plotext#5]
There is another problem, if i want to plot a datastream that only contains zeros it throws an exception and not plotting anything.

I tried this:
```
plx.scatter([0,0,0])
plx.show()
```

and got this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\plotext\plot.py", line 48, in show
    _set_grid()
  File "C:\Program Files\Python37\lib\site-packages\plotext\plot.py", line 324, in _set_grid
    _add_to_grid(_vars.x[s], _vars.y[s], _vars.point_marker[s], _vars.point_color[s])
  File "C:\Program Files\Python37\lib\site-packages\plotext\plot.py", line 350, in _add_to_grid
    r = int((y[n] - _vars.ymin) / _vars.dy)
ZeroDivisionError: float division by zero
```

If I set the ylim to something this issue does not occur.

**Comment by piccolomo** [comment]
Dear  Schmetzler ,
thanks for this bug report as well.

I have now resolved this issue but not publish it yet. I will in the next version, which will have the real data coordinates as axis ticks and will take some time. 

Any other bug report is more then welcomed! :-)

Savino

**Comment by piccolomo** [comment]
Dear Schmetzler ,

thanks for reporting the issue. 

Luckily, I have just upgraded the package, also solving this issue.

Here is the code:
```
plt.plot([0, 0, 0])
plt.set_canvas_size(100, 30) # not necessary but it makes the plot easier to upload here
plt.show()
```
and here is the plot:
```                                                                                                    ├ 1   
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    ├ 0.5 
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
•                                                •                                                 •├ 0   
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    ├ -0.5
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    │     
                                                                                                    ├ -1  
┬────────────────────────┬───────────────────────┬────────────────────────┬────────────────────────┬┘     
0                        0.5                     1                        1.5                      2   ```

which outputs what you would expect. 

You can upgrade your `plotext` version using `pip install plotext --upgrade` and acess the package documentation at[ pypi:plotext ](https://pypi.org/project/plotext/)and [github:plotext](https://github.com/piccolomo/plotext). 
The package has been just upgraded so there may be further issues: feel free to report any other, cause it is helpful! :-)

I hope it was useful and all the best using the package !

Savino
