### ISSUE TITLE
Packages Dependencies Missing in Version 4.0.0

### ISSUE THREAD

**Issue by jtplaarj** [piccolomo/plotext#53]
When trying to execute the command line example (or any other code that worked in previous version) the following error appears:

```bash
python3 -c "import plotext as plt; y=plt.sin(); plt.clp(); plt.scatter(y); plt.title('Scatter Plot'); plt.show();"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/plotext/.venv/lib/python3.8/site-packages/plotext/__init__.py", line 3, in <module>
    from plotext._core import *
  File "/tmp/plotext/.venv/lib/python3.8/site-packages/plotext/_core.py", line 14, in <module>
    from plotext._figure import figure_class as _figure_class
  File "/tmp/plotext/.venv/lib/python3.8/site-packages/plotext/_figure.py", line 9, in <module>
    from plotext._subplot import subplot_class
  File "/tmp/plotext/.venv/lib/python3.8/site-packages/plotext/_subplot.py", line 7, in <module>
    from plotext._utility.image import *
  File "/tmp/plotext/.venv/lib/python3.8/site-packages/plotext/_utility/image.py", line 2, in <module>
    from PIL.Image import fromarray
ModuleNotFoundError: No module named 'PIL'
```

It also happens with Python 3.9.

**Comment by jtplaarj** [comment]
I think that there are a couple of requirements missing:

- Pillow
- numpy

**Comment by piccolomo** [comment]
Do you have Pillow installed?

**Comment by jtplaarj** [comment]
Once I install Pillow the problem is solved, but it is not automatically installed as a dependency by pip.

**Comment by piccolomo** [comment]
Thanks, I added the following line to setup.py:

install_requires=['numpy', 'Pillow'],

and needs to modify the readme too. I will do it once enough changes accumulate. Thanks!!!

**Comment by piccolomo** [comment]
Hi @jtplaarj   ,

thanks a lot for the issue report. I should have sorted this in the newly updated 4.1.0 version, available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/).

Thanks and all the best,
Savino.
