### ISSUE TITLE
Making a barplot where all entries have the same height results in a division by zero.

### ISSUE THREAD

**Issue by SoyBison** [piccolomo/plotext#61]
Minimal example included

```python
plt.bar(['a', 'b', 'c'], [1,1,1])
plt.show()
Traceback (most recent call last):
  File "/home/coen/Documents/Macrohard/ProjectRatio/FramingSelection/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-1eb00ff78cf2>", line 1, in <module>
    plt.show()
  File "/home/coen/Documents/Macrohard/ProjectRatio/FramingSelection/venv/lib/python3.9/site-packages/plotext/_figure.py", line 281, in show
    self.build()
  File "/home/coen/Documents/Macrohard/ProjectRatio/FramingSelection/venv/lib/python3.9/site-packages/plotext/_figure.py", line 266, in build
    self.subplot.get_absolute_ticks()
  File "/home/coen/Documents/Macrohard/ProjectRatio/FramingSelection/venv/lib/python3.9/site-packages/plotext/_subplot.py", line 271, in get_absolute_ticks
    self.rticks = [get_matrix_data(self.yticks[s], self.ylim[s], self.height_canvas) for s in range(2)]
  File "/home/coen/Documents/Macrohard/ProjectRatio/FramingSelection/venv/lib/python3.9/site-packages/plotext/_subplot.py", line 271, in <listcomp>
    self.rticks = [get_matrix_data(self.yticks[s], self.ylim[s], self.height_canvas) for s in range(2)]
  File "/home/coen/Documents/Macrohard/ProjectRatio/FramingSelection/venv/lib/python3.9/site-packages/plotext/_utility/plot.py", line 30, in get_matrix_data
    data = [round((el - lim[0]) / dz + 0.5, 1)   for el in data]
  File "/home/coen/Documents/Macrohard/ProjectRatio/FramingSelection/venv/lib/python3.9/site-packages/plotext/_utility/plot.py", line 30, in <listcomp>
    data = [round((el - lim[0]) / dz + 0.5, 1)   for el in data]
ZeroDivisionError: float division by zero
```

**Comment by piccolomo** [comment]
Hi @SoyBison,

thanks a lot for the issue report. I have sorted the issue in the new version 4.1.0 available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/).

Now 
```
plt.bar(['a', 'b', 'c'], [1,1,1])
plt.show()
```
should outupt:
![image](https://user-images.githubusercontent.com/56689657/145540411-d79c23fc-d6fa-4616-ac0d-403a046ba11d.png)

Feel free to reopen it this or a new issue remains. 

Savino.
