### ISSUE TITLE
Single Bar Plot: division by zero error (also in Pull 43)

### ISSUE THREAD

**Issue by JakubFrejlach** [piccolomo/plotext#63]
Miminal example:
```python
plt.bar(["a"],[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jfrejlac/school/PDI/project/venv/lib64/python3.9/site-packages/plotext/_core.py", line 197, in bar
    figure.subplot.draw_single_bar(x, y,
  File "/home/jfrejlac/school/PDI/project/venv/lib64/python3.9/site-packages/plotext/_subplot.py", line 429, in draw_single_bar
    xbar, ybar = bars(x, y, width, self.bar_ylim[0])
  File "/home/jfrejlac/school/PDI/project/venv/lib64/python3.9/site-packages/plotext/_utility/bar.py", line 54, in bars
    bin_size_half = (max(x) - min(x)) / (bins - 1) * width / 2
ZeroDivisionError: division by zero
```

**Comment by piccolomo** [comment]
Hi @JakubFrejlach,

thanks for the issue report. The error is due to the fact that only a single bar is plotted, instead of the height being 1.

The issue was noted and fixed in [Pull 43](https://github.com/piccolomo/plotext/pull/43) but unfortunately the repo history got broken and the changes lost.

Anyway the new version [4.1.4](https://github.com/piccolomo/plotext) (available for now only on GitHub) should fix this issue.

Thanks,
Savino
