### ISSUE TITLE
Streaming Data not working in version 5.0

### ISSUE THREAD

**Issue by spring-cxz** [piccolomo/plotext#99]
Hi , I want to use streaming data mode to show some data, but is not working, It's blocked in the beginning. 

The code is like this 

```
import plotext as plt
import time

l = 1
while l < 10000000000:
    l *= 2
    y.append(l)

    plt.cld()
    plt.clt()

    plt.plot(y)
    plt.show()

    time.sleep(1)
```

^CTraceback (most recent call last):
  File "draw2.py", line 21, in <module>
    plt.show()
  File "/usr/local/lib/python3.7/dist-packages/plotext/_core.py", line 183, in show
    figure.show()
  File "/usr/local/lib/python3.7/dist-packages/plotext/_figure.py", line 250, in show
    self.build()
  File "/usr/local/lib/python3.7/dist-packages/plotext/_figure.py", line 257, in build
    self._build_matrix()
  File "/usr/local/lib/python3.7/dist-packages/plotext/_figure.py", line 283, in _build_matrix
    self.monitor.build_plot(*self._size) if not self.monitor.fast_plot else None
  File "/usr/local/lib/python3.7/dist-packages/plotext/_monitor.py", line 847, in build_plot
    x[s], y[s], mxy = hd_group(x[s], y[s], xf[s], yf[s])
  File "/usr/local/lib/python3.7/dist-packages/plotext/_monitor.py", line 1191, in hd_group
    m = [[[r[:] for r in m0] for x in range(lx)] for y in range(ly)]
  File "/usr/local/lib/python3.7/dist-packages/plotext/_monitor.py", line 1191, in <listcomp>
    m = [[[r[:] for r in m0] for x in range(lx)] for y in range(ly)]
  File "/usr/local/lib/python3.7/dist-packages/plotext/_monitor.py", line 1191, in <listcomp>
    m = [[[r[:] for r in m0] for x in range(lx)] for y in range(ly)]
  File "/usr/local/lib/python3.7/dist-packages/plotext/_monitor.py", line 1191, in <listcomp>
    m = [[[r[:] for r in m0] for x in range(lx)] for y in range(ly)]
KeyboardInterrupt

![image](https://user-images.githubusercontent.com/52104372/177731055-0d2c48a0-bcdd-4b53-a06c-7d321beeeea1.png)

Thanks.

**Comment by spring-cxz** [comment]
I used pip3 to install it . And a new issue appeared.

![image](https://user-images.githubusercontent.com/52104372/177756800-eeda564f-6665-4613-8116-89ec8ddd20e0.png)

**Comment by spring-cxz** [comment]
My run it on  Debian 9 in Virtual Box.  I'll have a try again. Thanks .

**Comment by piccolomo** [comment]
Try to get the version of Python you are using (it doesn't seem to like the unpacking operator *), also try to remove the warning shown by not running as administrator, even tough I tried to run it myself as administrator and worked just fine. 
Good luck

**Comment by spring-cxz** [comment]
There is a good news. It works after update python 3.7  to 3.8 version.   So there is something wrong on python 3.7.
Plotext is a good module, I like it.
Thanks very much.  :)

**Comment by piccolomo** [comment]
Hi @spring-cxz , I finally updated `plotext` and the new version should solve this issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino
